name: Destroy Gitea Infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy the Gitea infrastructure'
        default: 'false'

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.destroy == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          export ARM_CLIENT_ID="${{ secrets.ARM_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.ARM_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.ARM_TENANT_ID }}"
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          
      - name: Create SSH directory if not exists
        run: mkdir -p $HOME/.ssh

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/.ssh/gitea.pub
        shell: bash
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"
        working-directory: terraform

      - name: Terraform Destroy VM
        run: terraform destroy -target=azurerm_linux_virtual_machine.gitea_vm -auto-approve
        working-directory: terraform