name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Docker image to Package Registry
              run: |
                docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/gitea:${{ github.sha }} docker.pkg.github.com/${{ github.repository }}/${{ github.event_name }}/gitea:${{ github.sha }}
                docker push docker.pkg.github.com/${{ github.repository }}/${{ github.event_name }}/gitea:${{ github.sha }}
                DOCKER_IMAGE=ghcr.io/f-eighty7/devops_midterm_examination_project:${{ github.sha }}
                docker build -t $DOCKER_IMAGE .
                docker tag $DOCKER_IMAGE ghcr.io/f-eighty7/devops_midterm_examination_project/gitea:latest
                docker push $DOCKER_IMAGE
                docker push ghcr.io/f-eighty7/devops_midterm_examination_project/gitea:latest