name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Docker image to Package Registry
              run: |
                REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
                DOCKER_IMAGE=ghcr.io/$REPO_NAME/gitea:${{ github.sha }}
                docker build -t $DOCKER_IMAGE .
                docker tag $DOCKER_IMAGE ghcr.io/$REPO_NAME/gitea:latest
                docker push $DOCKER_IMAGE
                docker push ghcr.io/$REPO_NAME/gitea:latest
                echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV