name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Push Docker image to Package Registry
              run: |
                docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/gitea:${{ github.sha }} docker.pkg.github.com/${{ github.repository }}/${{ github.event_name }}/gitea:${{ github.sha }}
                sdocker push docker.pkg.github.com/${{ github.repository }}/${{ github.event_name }}/gitea:${{ github.sha }}