name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            
      
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push Docker image to Package Registry
              run: |
                docker build . --tag ghcr.io/f-eighty7/devops_midterm_examination_project/gitea:latest
                docker push ghcr.io/f-eighty7/devops_midterm_examination_project/gitea:latest